" Logic
imap <buffer> <LocalLeader>all ∀
imap <buffer> <LocalLeader>forall ∀
imap <buffer> <LocalLeader>ex ∃
imap <buffer> <LocalLeader>iff ↔
imap <buffer> <LocalLeader>land ∧
imap <buffer> <LocalLeader>lor ∨
imap <buffer> <LocalLeader>le ≤
imap <buffer> <LocalLeader>ge ≥
imap <buffer> <LocalLeader>neg ¬
imap <buffer> <LocalLeader>/= ≠
imap <buffer> <LocalLeader>to →
imap <buffer> <LocalLeader>-> →
imap <buffer> <C-_> →
imap <buffer> <LocalLeader>{ ⦃⦄<Left>
imap <buffer> <LocalLeader>} ⦄<Left>
imap <buffer> <LocalLeader>in ∈
imap <buffer> <LocalLeader>\|- ⊢

" Greek (lower)
imap <buffer> <LocalLeader>alpha α
imap <buffer> <LocalLeader>a α
imap <buffer> <LocalLeader>beta β
imap <buffer> <LocalLeader>b β
imap <buffer> <LocalLeader>gamma γ
imap <buffer> <LocalLeader>g γ
imap <buffer> <LocalLeader>delta δ
imap <buffer> <LocalLeader>d δ
imap <buffer> <LocalLeader>epsilon ε
imap <buffer> <LocalLeader>e ε
imap <buffer> <LocalLeader>zeta ζ
imap <buffer> <LocalLeader>z ζ
imap <buffer> <LocalLeader>eta η
imap <buffer> <LocalLeader>h η
imap <buffer> <LocalLeader>theta θ
imap <buffer> <LocalLeader>iota ι
imap <buffer> <LocalLeader>i ι
imap <buffer> <LocalLeader>kappa κ
imap <buffer> <LocalLeader>k κ
imap <buffer> <LocalLeader>lambda λ
imap <buffer> <LocalLeader>L λ
imap <buffer> <LocalLeader>mu μ
imap <buffer> <LocalLeader>m μ
imap <buffer> <LocalLeader>nu ν
imap <buffer> <LocalLeader>n ν
imap <buffer> <LocalLeader>xi ξ
imap <buffer> <LocalLeader>omicron ο
imap <buffer> <LocalLeader>pi π
imap <buffer> <LocalLeader>p π
imap <buffer> <LocalLeader>rho ρ
imap <buffer> <LocalLeader>r ρ
imap <buffer> <LocalLeader>sigma σ
imap <buffer> <LocalLeader>s σ
imap <buffer> <LocalLeader>varsigma ς
imap <buffer> <LocalLeader>vars ς
imap <buffer> <LocalLeader>tau τ
imap <buffer> <LocalLeader>t τ
imap <buffer> <LocalLeader>u υ
imap <buffer> <LocalLeader>phi φ
imap <buffer> <LocalLeader>f φ
imap <buffer> <LocalLeader>chi χ
imap <buffer> <LocalLeader>x χ
imap <buffer> <LocalLeader>psi ψ
imap <buffer> <LocalLeader>c ψ
imap <buffer> <LocalLeader>omega ω
imap <buffer> <LocalLeader>v ω

" Greek (upper)
imap <buffer> <LocalLeader>Alpha Α
imap <buffer> <LocalLeader>Beta Β
imap <buffer> <LocalLeader>G Γ
imap <buffer> <LocalLeader>D Δ
imap <buffer> <LocalLeader>Epsilon Ε
imap <buffer> <LocalLeader>Zeta Ζ
imap <buffer> <LocalLeader>Eta Η
imap <buffer> <LocalLeader>Theta Θ
imap <buffer> <LocalLeader>Iota Ι
imap <buffer> <LocalLeader>Kappa Κ
imap <buffer> <LocalLeader>Lambda Λ
imap <buffer> <LocalLeader>Mu Μ
imap <buffer> <LocalLeader>Nu Ν
imap <buffer> <LocalLeader>Xi Ξ
imap <buffer> <LocalLeader>Omicron Ο
imap <buffer> <LocalLeader>P Π
imap <buffer> <LocalLeader>Rho Ρ
imap <buffer> <LocalLeader>S Σ
imap <buffer> <LocalLeader>Tau Τ
imap <buffer> <LocalLeader>Upsilon Υ
imap <buffer> <LocalLeader>Phi Φ
imap <buffer> <LocalLeader>F Φ
imap <buffer> <LocalLeader>Chi Χ
imap <buffer> <LocalLeader>Psi Ψ
imap <buffer> <LocalLeader>Omega Ω

" Subscripts
imap <buffer> <LocalLeader>0 ₀
imap <buffer> <LocalLeader>1 ₁
imap <buffer> <LocalLeader>2 ₂
imap <buffer> <LocalLeader>3 ₃
imap <buffer> <LocalLeader>4 ₄
imap <buffer> <LocalLeader>5 ₅
imap <buffer> <LocalLeader>6 ₆
imap <buffer> <LocalLeader>7 ₇
imap <buffer> <LocalLeader>8 ₈
imap <buffer> <LocalLeader>9 ₉

" Logic
cmap <buffer> <LocalLeader>all ∀
cmap <buffer> <LocalLeader>forall ∀
cmap <buffer> <LocalLeader>ex ∃
cmap <buffer> <LocalLeader>iff ↔
cmap <buffer> <LocalLeader>land ∧
cmap <buffer> <LocalLeader>lor ∨
cmap <buffer> <LocalLeader>le ≤
cmap <buffer> <LocalLeader>ge ≥
cmap <buffer> <LocalLeader>neg ¬
cmap <buffer> <LocalLeader>/= ≠
cmap <buffer> <LocalLeader>to →
cmap <buffer> <LocalLeader>-> →
cmap <buffer> <C-_> →
cmap <buffer> <LocalLeader>{ ⦃⦄<Left>
cmap <buffer> <LocalLeader>} ⦄<Left>
cmap <buffer> <LocalLeader>in ∈
cmap <buffer> <LocalLeader>\|- ⊢

" Greek (lower)
cmap <buffer> <LocalLeader>alpha α
cmap <buffer> <LocalLeader>a α
cmap <buffer> <LocalLeader>beta β
cmap <buffer> <LocalLeader>b β
cmap <buffer> <LocalLeader>gamma γ
cmap <buffer> <LocalLeader>g γ
cmap <buffer> <LocalLeader>delta δ
cmap <buffer> <LocalLeader>d δ
cmap <buffer> <LocalLeader>epsilon ε
cmap <buffer> <LocalLeader>e ε
cmap <buffer> <LocalLeader>zeta ζ
cmap <buffer> <LocalLeader>z ζ
cmap <buffer> <LocalLeader>eta η
cmap <buffer> <LocalLeader>h η
cmap <buffer> <LocalLeader>theta θ
cmap <buffer> <LocalLeader>iota ι
cmap <buffer> <LocalLeader>i ι
cmap <buffer> <LocalLeader>kappa κ
cmap <buffer> <LocalLeader>k κ
cmap <buffer> <LocalLeader>lambda λ
cmap <buffer> <LocalLeader>L λ
cmap <buffer> <LocalLeader>mu μ
cmap <buffer> <LocalLeader>m μ
cmap <buffer> <LocalLeader>nu ν
cmap <buffer> <LocalLeader>n ν
cmap <buffer> <LocalLeader>xi ξ
cmap <buffer> <LocalLeader>omicron ο
cmap <buffer> <LocalLeader>pi π
cmap <buffer> <LocalLeader>p π
cmap <buffer> <LocalLeader>rho ρ
cmap <buffer> <LocalLeader>r ρ
cmap <buffer> <LocalLeader>sigma σ
cmap <buffer> <LocalLeader>s σ
cmap <buffer> <LocalLeader>varsigma ς
cmap <buffer> <LocalLeader>vars ς
cmap <buffer> <LocalLeader>tau τ
cmap <buffer> <LocalLeader>t τ
cmap <buffer> <LocalLeader>u υ
cmap <buffer> <LocalLeader>phi φ
cmap <buffer> <LocalLeader>f φ
cmap <buffer> <LocalLeader>chi χ
cmap <buffer> <LocalLeader>x χ
cmap <buffer> <LocalLeader>psi ψ
cmap <buffer> <LocalLeader>c ψ
cmap <buffer> <LocalLeader>omega ω
cmap <buffer> <LocalLeader>v ω

" Greek (upper)
cmap <buffer> <LocalLeader>Alpha Α
cmap <buffer> <LocalLeader>Beta Β
cmap <buffer> <LocalLeader>G Γ
cmap <buffer> <LocalLeader>D Δ
cmap <buffer> <LocalLeader>Epsilon Ε
cmap <buffer> <LocalLeader>Zeta Ζ
cmap <buffer> <LocalLeader>Eta Η
cmap <buffer> <LocalLeader>Theta Θ
cmap <buffer> <LocalLeader>Iota Ι
cmap <buffer> <LocalLeader>Kappa Κ
cmap <buffer> <LocalLeader>Lambda Λ
cmap <buffer> <LocalLeader>Mu Μ
cmap <buffer> <LocalLeader>Nu Ν
cmap <buffer> <LocalLeader>Xi Ξ
cmap <buffer> <LocalLeader>Omicron Ο
cmap <buffer> <LocalLeader>P Π
cmap <buffer> <LocalLeader>Rho Ρ
cmap <buffer> <LocalLeader>S Σ
cmap <buffer> <LocalLeader>Tau Τ
cmap <buffer> <LocalLeader>Upsilon Υ
cmap <buffer> <LocalLeader>Phi Φ
cmap <buffer> <LocalLeader>F Φ
cmap <buffer> <LocalLeader>Chi Χ
cmap <buffer> <LocalLeader>Psi Ψ
cmap <buffer> <LocalLeader>Omega Ω

" Subscripts
cmap <buffer> <LocalLeader>0 ₀
cmap <buffer> <LocalLeader>1 ₁
cmap <buffer> <LocalLeader>2 ₂
cmap <buffer> <LocalLeader>3 ₃
cmap <buffer> <LocalLeader>4 ₄
cmap <buffer> <LocalLeader>5 ₅
cmap <buffer> <LocalLeader>6 ₆
cmap <buffer> <LocalLeader>7 ₇
cmap <buffer> <LocalLeader>8 ₈
cmap <buffer> <LocalLeader>9 ₉
